# exploring enron

In [1]:


%matplotlib inline
import pickle
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from operator import itemgetter
from IPython.core.display import HTML
pd.set_option('display.max_rows', 5000)

/Users/stunglan2/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

In [2]:


enron_data = pickle.load(open("../ud120-projects/final_project/final_project_dataset.pkl", "r"))

In [3]:
def print_quiz_answer(str):
    return HTML('<div style="color:#0000FF">QUIZ Anwer:  </dic><div style="color:#FF00FF">{}</dic>'.format(str))

In [4]:
enron_df = pd.DataFrame(enron_data)
enron_df_t = enron_df.transpose()

In [5]:
print_quiz_answer('number of persons: {}'.format(len(enron_df_t)))

In [6]:
print_quiz_answer('number of features: {}'.format(len(enron_df_t.columns)))

In [7]:
s = len(enron_df_t[enron_df_t['poi']])
print_quiz_answer('number of persons of interest: {}'.format(s))

In [8]:
# read text files with names
fname = '../ud120-projects/final_project/poi_names.txt'
with open(fname) as f:
    content = f.readlines()

#skip two first lines
content = content[2:]

#find the values
persons = []

for lines in content:
    m = re.match('\((?P<_0>.+)\) (?P<_1>.+)\, (?P<_2>.+)\n', lines)
    persons.append(map(itemgetter(1), sorted(m.groupdict().items())))

s = len(persons)
print_quiz_answer('number of persons of interest in text file: {}'.format(s))

In [9]:
s = enron_df_t.loc["PRENTICE JAMES",'total_stock_value']
print_quiz_answer('the total value of the stock belonging to James Prentice: {}'.format(s))

In [10]:
s= enron_df_t.loc["COLWELL WESLEY",'from_this_person_to_poi']
print_quiz_answer('email messages do we have from Wesley Colwell to persons of interest: {}'.format(s))

In [11]:
s = enron_df_t.loc["SKILLING JEFFREY K",'exercised_stock_options']
print_quiz_answer('the value of stock options exercised by Jeffrey K Skilling?: {}'.format(s))

In [64]:
s = enron_df.loc['exercised_stock_options',"SKILLING JEFFREY K"]
print_quiz_answer('the value of stock options exercised by Jeffrey K Skilling?: {}'.format(s))

reading wikipedia 
https://en.wikipedia.org/wiki/Enron_scandal

In [61]:
s = enron_df_t.ix[:,'total_payments']
type(s)
s = s.sort_values(ascending=False,na_position='last')
major = ["SKILLING JEFFREY K","LAY KENNETH L","FASTOW ANDREW S"] 
s

HUGHES JAMES A                         NaN
LEWIS RICHARD                          NaN
SCRIMSHAW MATTHEW                      NaN
POWERS WILLIAM                         NaN
CHRISTODOULOU DIOMEDES                 NaN
PIRO JIM                               NaN
SHERRICK JEFFREY B                     NaN
MORAN MICHAEL P                        NaN
MCDONALD REBECCA                       NaN
CHAN RONNIE                            NaN
MCCARTY DANNY J                        NaN
HAYSLETT RODERICK J                    NaN
LOWRY CHARLES P                        NaN
CORDES WILLIAM R                       NaN
LOCKHART EUGENE E                      NaN
CLINE KENNETH W                        NaN
GATHMANN WILLIAM D                     NaN
WROBEL BRUCE                           NaN
GILLIS JOHN                            NaN
WHALEY DAVID A                         NaN
FOWLER PEGGY                           NaN
TOTAL                            309886585
LAY KENNETH L                    103559793
FREVERT MARK A                    17252530
BHATNAGAR SANJAY                  15456290
LAVORATO JOHN J                   10425757
SKILLING JEFFREY K                 8682716
MARTIN AMANDA K                    8407016
BAXTER JOHN C                      5634343
BELDEN TIMOTHY N                   5501630
DELAINEY DAVID W                   4747979
WHALLEY LAWRENCE G                 4677574
ALLEN PHILLIP K                    4484442
SHERRIFF JOHN R                    4335388
MCMAHON JEFFREY                    4099771
HAEDICKE MARK E                    3859065
FALLON JAMES B                     3676340
KITCHEN LOUISE                     3471141
MULLER MARK S                      3202070
HORTON STANLEY C                   3131860
PAI LOU L                          3123383
HUMPHREY GENE E                    3100224
SHANKMAN JEFFREY A                 3038702
ECHOLS JOHN B                      2692324
BOWEN JR RAYMOND M                 2669589
LEFF DANIEL P                      2664228
KOPPER MICHAEL J                   2652612
FASTOW ANDREW S                    2424083
DIMICHELE RICHARD G                2368151
BUY RICHARD B                      2355702
GOLD JOSEPH                        2146973
MCCONNELL MICHAEL S                2101364
DURAN WILLIAM D                    2093263
HICKERSON GARY J                   2081796
BIBI PHILIPPE A                    2047593
BLACHMAN JEREMY M                  2014835
SHELBY REX                         2003885
IZZO LAWRENCE L                    1979596
WHITE JR THOMAS E                  1934359
CAUSEY RICHARD A                   1868758
MEYER ROCKFORD G                   1848227
WALLS JR ROBERT H                  1798780
KEAN STEVEN J                      1747522
PIPER GREGORY F                    1737629
CALGER CHRISTOPHER F               1639297
KOENIG MARK E                      1587421
SHARP VICTORIA T                   1576511
GARLAND C KEVIN                    1566469
SUNDE MARTIN                       1545059
COLWELL WESLEY                     1490344
FITZGERALD JAY L                   1414857
DIETRICH JANET R                   1410464
PICKERING MARK R                   1386690
OLSON CINDY K                      1321557
MCCLELLAN GEORGE                   1318763
HERMANN ROBERT J                   1297461
GLISAN JR BEN F                    1272284
BUTTS ROBERT H                     1271582
DEFFNER JOSEPH M                   1208649
DETMERING TIMOTHY J                1204583
GRAY RODNEY                        1146658
UMANOFF ADAM S                     1130461
STABLER FRANK                      1112087
COX DAVID                          1101393
RIEKER PAULA H                     1099100
TAYLOR MITCHELL S                  1092663
KAMINSKI WINCENTY J                1086821
METTS MARK                         1061827
SHAPIRO RICHARD S                  1057548
BUCHANAN HAROLD G                  1054637
WASAFF GEORGE                      1034395
SULLIVAN-SHAKLOVITZ COLLEEN         999356
BECK SALLY W                        969068
GIBBS DANA R                        966522
BANNANTINE JAMES M                  916197
THORN TERENCE H                     911453
GAHN ROBERT S                       900585
LINDHOLM TOD A                      875889
DONAHUE JR JEFFREY M                875760
BAZELIDES PHILIP J                  860136
BAY FRANKLIN R                      827696
MURRAY JULIA H                      812194
CUMBERLAND MICHAEL S                807956
NOLES JAMES L                       774401
WESTFAHL RICHARD K                  762135
KISHKILL JOSEPH G                   704896
MORDAUNT KRISTINA M                 628522
BERGSIEKER RICHARD P                618850
PRENTICE JAMES                      564348
JACKSON CHARLENE R                  551174
DERRICK JR. JAMES V                 550981
RICE KENNETH D                      505050
CARTER REBECCA C                    477557
TILNEY ELIZABETH A                  399393
REYNOLDS LAWRENCE                   394475
THE TRAVEL AGENCY IN THE PARK       362096
YEAGER F SCOTT                      360300
DODSON KEITH                        319941
HANNON KEVIN P                      288682
OVERDYKE JR JERE C                  249787
URQUHART JOHN A                     228656
BERBERIAN DAVID                     228474
WAKEHAM JOHN                        213071
ELLIOTT STEVEN                      211725
WODRASKA JOHN                       189583
BADUM JAMES P                       182466
FOY JOE                             181755
GRAMM WENDY L                       119292
REDMOND BRIAN L                     111529
BELFER ROBERT                       102500
HIRKO JOSEPH                         91093
LEMAISTRE CHARLES                    87492
WALTERS GARETH W                     87410
WINOKUR JR. HERBERT S                84992
JAEDICKE ROBERT                      83750
DUNCAN JOHN H                        77492
YEAP SOON                            55097
FUGH JOHN L                          50591
BROWN MICHAEL                        49288
PEREIRA PAULO V. FERRAZ              27942
HAYES ROBERT E                        7961
SAVAGE FRANK                          3750
MEYER JEROME J                        2151
BLAKE JR. NORMAN P                    1279
HAUG DAVID L                           475
MENDELSOHN JOHN                        148
Name: total_payments, dtype: object

In [95]:
cxo = []
for row_index, row in enron_df_t.iterrows():
    if row_index in major:
        #print('%s\n%s' % (row_index, row.total_payments))
        cxo.append([row_index, row.total_payments])

cxo = pd.DataFrame(cxo)
cxo = cxo.sort_values(by=1,ascending=False)
cxo[0:1][0]
print_quiz_answer('top earner: {}, with {}'.format(cxo[0:1][0],cxo[0:1][1]))

In [124]:

#np.isnan(enron_df_t.salary) 
type(enron_df_t.loc['BADUM JAMES P','salary'])

s = len(enron_df_t[enron_df_t['salary'] <> 'NaN'])
print_quiz_answer('number of persons with salary: {}'.format(s))

In [126]:
s = len(enron_df_t[enron_df_t['email_address'] <> 'NaN'])
print_quiz_answer('number of persons with email: {}'.format(s))

In [162]:
s = len(enron_df_t[(enron_df_t.total_payments == 'NaN')])+10
l = 100.0*s/(len(enron_df_t)+10)
print_quiz_answer('number of persons without total payments: {}, percent: {:.2f}'.format(s,l))

In [160]:
s = len(enron_df_t[(enron_df_t.total_payments == 'NaN') & (enron_df_t.poi)])
l = 100.0*s/len(enron_df_t[enron_df_t['poi']])
print_quiz_answer('number of persons without total payments: {}, percent: {:.2f}'.format(s,l))

In [161]:
s = len(enron_df_t[(enron_df_t.total_payments == 'NaN') & (enron_df_t.poi)])+10
l = 100.0*s/(len(enron_df_t[enron_df_t['poi']])+10)
print_quiz_answer('number of persons without total payments: {}, percent: {:.2f}'.format(s,l))

In [129]:
enron_df_t

,bonus,deferral_payments,deferred_income,director_fees,email_address,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,from_this_person_to_poi,...,long_term_incentive,other,poi,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value
ALLEN PHILLIP K,4175000,2869717,-3081055,NaN,phillip.allen@enron.com,1729541,13868,2195,47,65,...,304805,152,False,126027,-126027,201955,1407,2902,4484442,1729541
BADUM JAMES P,NaN,178980,NaN,NaN,NaN,257817,3486,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,182466,257817
BANNANTINE JAMES M,NaN,NaN,-5104,NaN,james.bannantine@enron.com,4046157,56301,29,39,0,...,NaN,864523,False,1757552,-560222,477,465,566,916197,5243487
BAXTER JOHN C,1200000,1295738,-1386055,NaN,NaN,6680544,11200,NaN,NaN,NaN,...,1586055,2660303,False,3942714,NaN,267102,NaN,NaN,5634343,10623258
BAY FRANKLIN R,400000,260455,-201641,NaN,frank.bay@enron.com,NaN,129142,NaN,NaN,NaN,...,NaN,69,False,145796,-82782,239671,NaN,NaN,827696,63014
BAZELIDES PHILIP J,NaN,684694,NaN,NaN,NaN,1599641,NaN,NaN,NaN,NaN,...,93750,874,False,NaN,NaN,80818,NaN,NaN,860136,1599641
BECK SALLY W,700000,NaN,NaN,NaN,sally.beck@enron.com,NaN,37172,4343,144,386,...,NaN,566,False,126027,NaN,231330,2639,7315,969068,126027
BELDEN TIMOTHY N,5249999,2144013,-2334434,NaN,tim.belden@enron.com,953136,17355,484,228,108,...,NaN,210698,True,157569,NaN,213999,5521,7991,5501630,1110705
BELFER ROBERT,NaN,-102500,NaN,3285,NaN,3285,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,44093,NaN,NaN,NaN,102500,-44093
BERBERIAN DAVID,NaN,NaN,NaN,NaN,david.berberian@enron.com,1624396,11892,NaN,NaN,NaN,...,NaN,NaN,False,869220,NaN,216582,NaN,NaN,228474,2493616
BERGSIEKER RICHARD P,250000,NaN,-485813,NaN,rick.bergsieker@enron.com,NaN,59175,59,4,0,...,180250,427316,False,659249,NaN,187922,233,383,618850,659249
BHATNAGAR SANJAY,NaN,NaN,NaN,137864,sanjay.bhatnagar@enron.com,2604490,NaN,29,0,1,...,NaN,137864,False,-2604490,15456290,NaN,463,523,15456290,NaN
BIBI PHILIPPE A,1000000,NaN,NaN,NaN,philippe.bibi@enron.com,1465734,38559,40,23,8,...,369721,425688,False,378082,NaN,213625,1336,1607,2047593,1843816
BLACHMAN JEREMY M,850000,NaN,NaN,NaN,jeremy.blachman@enron.com,765313,84208,14,25,2,...,831809,272,False,189041,NaN,248546,2326,2475,2014835,954354
BLAKE JR. NORMAN P,NaN,NaN,-113784,113784,NaN,NaN,1279,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,1279,NaN
BOWEN JR RAYMOND M,1350000,NaN,-833,NaN,raymond.bowen@enron.com,NaN,65907,27,140,15,...,974293,1621,True,252055,NaN,278601,1593,1858,2669589,252055
BROWN MICHAEL,NaN,NaN,NaN,NaN,michael.brown@enron.com,NaN,49288,41,13,1,...,NaN,NaN,False,NaN,NaN,NaN,761,1486,49288,NaN
BUCHANAN HAROLD G,500000,NaN,NaN,NaN,john.buchanan@enron.com,825464,600,125,0,0,...,304805,1215,False,189041,NaN,248017,23,1088,1054637,1014505
BUTTS ROBERT H,750000,NaN,-75000,NaN,bob.butts@enron.com,NaN,9410,NaN,NaN,NaN,...,175000,150656,False,417619,NaN,261516,NaN,NaN,1271582,417619
BUY RICHARD B,900000,649584,-694862,NaN,rick.buy@enron.com,2542813,NaN,1053,156,71,...,769862,400572,False,901657,NaN,330546,2333,3523,2355702,3444470
CALGER CHRISTOPHER F,1250000,NaN,-262500,NaN,christopher.calger@enron.com,NaN,35818,144,199,25,...,375304,486,True,126027,NaN,240189,2188,2598,1639297,126027
CARTER REBECCA C,300000,NaN,-159792,NaN,rebecca.carter@enron.com,NaN,NaN,15,29,7,...,75000,540,False,307301,-307301,261809,196,312,477557,NaN
CAUSEY RICHARD A,1000000,NaN,-235000,NaN,richard.causey@enron.com,NaN,30674,49,58,12,...,350000,307895,True,2502063,NaN,415189,1585,1892,1868758,2502063
CHAN RONNIE,NaN,NaN,-98784,98784,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,False,32460,-32460,NaN,NaN,NaN,NaN,NaN
CHRISTODOULOU DIOMEDES,NaN,NaN,NaN,NaN,diomedes.christodoulou@enron.com,5127155,NaN,NaN,NaN,NaN,...,NaN,NaN,False,950730,NaN,NaN,NaN,NaN,NaN,6077885
CLINE KENNETH W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,False,662086,-472568,NaN,NaN,NaN,NaN,189518
COLWELL WESLEY,1200000,27610,-144062,NaN,wes.colwell@enron.com,NaN,16514,40,240,11,...,NaN,101740,True,698242,NaN,288542,1132,1758,1490344,698242
CORDES WILLIAM R,NaN,NaN,NaN,NaN,bill.cordes@enron.com,651850,NaN,12,10,0,...,NaN,NaN,False,386335,NaN,NaN,58,764,NaN,1038185
COX DAVID,800000,NaN,-41250,NaN,chip.cox@enron.com,117551,27861,33,0,4,...,NaN,494,False,378082,NaN,314288,71,102,1101393,495633
CUMBERLAND MICHAEL S,325000,NaN,NaN,NaN,NaN,NaN,22344,NaN,NaN,NaN,...,275000,713,False,207940,NaN,184899,NaN,NaN,807956,207940
DEFFNER JOSEPH M,600000,NaN,NaN,NaN,joseph.deffner@enron.com,17378,41626,74,115,4,...,335349,25553,False,141833,NaN,206121,552,714,1208649,159211
DELAINEY DAVID W,3000000,NaN,NaN,NaN,david.delainey@enron.com,2291113,86174,3069,66,609,...,1294981,1661,True,1323148,NaN,365163,2097,3093,4747979,3614261
DERRICK JR. JAMES V,800000,NaN,-1284000,NaN,james.derrick@enron.com,8831913,51124,909,64,20,...,484000,7482,False,1787380,-1787380,492375,1401,2181,550981,8831913
DETMERING TIMOTHY J,425000,875307,-775241,NaN,timothy.detmering@enron.com,2027865,52255,NaN,NaN,NaN,...,415657,1105,False,315068,-315068,210500,NaN,NaN,1204583,2027865
DIETRICH JANET R,600000,NaN,NaN,NaN,janet.dietrich@enron.com,1550019,3475,63,305,14,...,556416,473,False,315068,NaN,250100,1902,2572,1410464,1865087
DIMICHELE RICHARD G,1000000,NaN,NaN,NaN,richard.dimichele@enron.com,8191755,35812,NaN,NaN,NaN,...,694862,374689,False,126027,NaN,262788,NaN,NaN,2368151,8317782
DODSON KEITH,70000,NaN,NaN,NaN,keith.dodson@enron.com,NaN,28164,14,10,3,...,NaN,774,False,NaN,NaN,221003,114,176,319941,NaN
DONAHUE JR JEFFREY M,800000,NaN,-300000,NaN,jeff.donahue@enron.com,765920,96268,22,188,11,...,NaN,891,False,315068,NaN,278601,772,865,875760,1080988
DUNCAN JOHN H,NaN,NaN,-25000,102492,NaN,371750,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,77492,371750
DURAN WILLIAM D,750000,NaN,NaN,NaN,w.duran@enron.com,1451869,25785,12,106,3,...,1105218,1568,False,189041,NaN,210692,599,904,2093263,1640910
ECHOLS JOHN B,200000,NaN,NaN,NaN,john.echols@enron.com,601438,21530,NaN,NaN,NaN,...,2234774,53775,False,407503,NaN,182245,NaN,NaN,2692324,1008941
ELLIOTT STEVEN,350000,NaN,-400729,NaN,steven.elliott@enron.com,4890344,78552,NaN,NaN,NaN,...,NaN,12961,False,1788391,NaN,170941,NaN,NaN,211725,6678735
FALLON JAMES B,2500000,NaN,NaN,NaN,jim.fallon@enron.com,940257,95924,75,42,37,...,374347,401481,False,1392142,NaN,304588,1604,1755,3676340,2332399
FASTOW ANDREW S,1300000,NaN,-1386055,NaN,andrew.fastow@enron.com,NaN,55921,NaN,NaN,NaN,...,1736055,277464,True,1794412,NaN,440698,NaN,NaN,2424083,1794412
FITZGERALD JAY L,350000,NaN,NaN,NaN,jay.fitzgerald@enron.com,664461,23870,16,1,8,...,556416,285414,False,956775,NaN,199157,723,936,1414857,1621236
FOWLER PEGGY,NaN,NaN,NaN,NaN,kulvinder.fowler@enron.com,1324578,NaN,36,0,0,...,NaN,NaN,False,560170,NaN,NaN,10,517,NaN,1884748
FOY JOE,NaN,181755,NaN,NaN,tracy.foy@enron.com,343434,NaN,13,0,0,...,NaN,NaN,False,NaN,NaN,NaN,2,57,181755,343434
FREVERT MARK A,2000000,6426990,-3367011,NaN,mark.frevert@enron.com,10433518,86987,21,242,6,...,1617011,7427621,False,4188667,NaN,1060932,2979,3275,17252530,14622185
FUGH JOHN L,NaN,50591,NaN,NaN,NaN,176378,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,50591,176378
GAHN ROBERT S,509870,73122,-1042,NaN,NaN,83237,50080,NaN,NaN,NaN,...,NaN,76547,False,235370,NaN,192008,NaN,NaN,900585,318607
GARLAND C KEVIN,850000,NaN,NaN,NaN,kevin.garland@enron.com,636246,48405,44,10,27,...,375304,60814,False,259907,NaN,231946,178,209,1566469,896153
GATHMANN WILLIAM D,NaN,NaN,NaN,NaN,NaN,1753766,NaN,NaN,NaN,NaN,...,NaN,NaN,False,264013,-72419,NaN,NaN,NaN,NaN,1945360
GIBBS DANA R,NaN,504610,NaN,NaN,dana.gibbs@enron.com,2218275,NaN,12,0,0,...,461912,NaN,False,NaN,NaN,NaN,23,169,966522,2218275
GILLIS JOHN,NaN,NaN,NaN,NaN,NaN,9803,NaN,NaN,NaN,NaN,...,NaN,NaN,False,75838,NaN,NaN,NaN,NaN,NaN,85641
GLISAN JR BEN F,600000,NaN,NaN,NaN,ben.glisan@enron.com,384728,125978,16,52,6,...,71023,200308,True,393818,NaN,274975,874,873,1272284,778546
GOLD JOSEPH,750000,NaN,NaN,NaN,joe.gold@enron.com,436515,NaN,NaN,NaN,NaN,...,304805,819288,False,441096,NaN,272880,NaN,NaN,2146973,877611
GRAMM WENDY L,NaN,NaN,NaN,119292,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,119292,NaN
GRAY RODNEY,NaN,93585,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,365625,680833,False,NaN,NaN,6615,NaN,NaN,1146658,NaN
HAEDICKE MARK E,1150000,2157527,-934484,NaN,mark.haedicke@enron.com,608750,76169,1941,180,61,...,983346,52382,False,524169,-329825,374125,1847,4009,3859065,803094
HANNON KEVIN P,1500000,NaN,-3117011,NaN,kevin.hannon@enron.com,5538001,34039,32,32,21,...,1617011,11350,True,853064,NaN,243293,1035,1045,288682,6391065
HAUG DAVID L,NaN,NaN,NaN,NaN,david.haug@enron.com,NaN,475,19,4,7,...,NaN,NaN,False,2217299,NaN,NaN,471,573,475,2217299
HAYES ROBERT E,NaN,7961,NaN,NaN,robert.hayes@enron.com,NaN,NaN,12,16,0,...,NaN,NaN,False,151418,NaN,NaN,50,504,7961,151418
HAYSLETT RODERICK J,NaN,NaN,NaN,NaN,rod.hayslett@enron.com,NaN,NaN,1061,35,38,...,NaN,NaN,False,346663,NaN,NaN,571,2649,NaN,346663
HERMANN ROBERT J,700000,NaN,-280000,NaN,robert.hermann@enron.com,187500,48357,NaN,NaN,NaN,...,150000,416441,False,480632,NaN,262663,NaN,NaN,1297461,668132
HICKERSON GARY J,1700000,NaN,NaN,NaN,gary.hickerson@enron.com,NaN,98849,27,40,1,...,69223,1936,False,441096,NaN,211788,900,1320,2081796,441096
HIRKO JOSEPH,NaN,10259,NaN,NaN,joe.hirko@enron.com,30766064,77978,NaN,NaN,NaN,...,NaN,2856,True,NaN,NaN,NaN,NaN,NaN,91093,30766064
HORTON STANLEY C,NaN,3131860,NaN,NaN,stanley.horton@enron.com,5210569,NaN,1073,44,15,...,NaN,NaN,False,2046079,NaN,NaN,1074,2350,3131860,7256648
HUGHES JAMES A,NaN,NaN,NaN,NaN,james.hughes@enron.com,754966,NaN,34,35,5,...,NaN,NaN,False,363428,NaN,NaN,589,719,NaN,1118394
HUMPHREY GENE E,NaN,2964506,NaN,NaN,gene.humphrey@enron.com,2282768,4994,17,10,17,...,NaN,NaN,False,NaN,NaN,130724,119,128,3100224,2282768
IZZO LAWRENCE L,NaN,NaN,NaN,NaN,larry.izzo@enron.com,2165172,28093,19,28,5,...,312500,1553729,False,3654808,NaN,85274,437,496,1979596,5819980
JACKSON CHARLENE R,250000,NaN,NaN,NaN,charlene.jackson@enron.com,185063,10181,56,25,19,...,NaN,2435,False,540672,NaN,288558,117,258,551174,725735
JAEDICKE ROBERT,NaN,NaN,-25000,108750,NaN,431750,NaN,NaN,NaN,NaN,...,NaN,NaN,False,44093,-44093,NaN,NaN,NaN,83750,431750
KAMINSKI WINCENTY J,400000,NaN,NaN,NaN,vince.kaminski@enron.com,850010,83585,14368,41,171,...,323466,4669,False,126027,NaN,275101,583,4607,1086821,976037
KEAN STEVEN J,1000000,NaN,NaN,NaN,steven.kean@enron.com,2022048,41953,6759,140,387,...,300000,1231,False,4131594,NaN,404338,3639,12754,1747522,6153642
KISHKILL JOSEPH G,NaN,NaN,-51042,NaN,joe.kishkill@enron.com,NaN,116335,NaN,NaN,NaN,...,NaN,465357,False,1034346,NaN,174246,NaN,NaN,704896,1034346
KITCHEN LOUISE,3100000,NaN,NaN,NaN,louise.kitchen@enron.com,81042,5774,1728,251,194,...,NaN,93925,False,466101,NaN,271442,3669,8305,3471141,547143
KOENIG MARK E,700000,NaN,NaN,NaN,mark.koenig@enron.com,671737,127017,61,53,15,...,300000,150458,True,1248318,NaN,309946,2271,2374,1587421,1920055
KOPPER MICHAEL J,800000,NaN,NaN,NaN,michael.kopper@enron.com,NaN,118134,NaN,NaN,NaN,...,602671,907502,True,985032,NaN,224305,NaN,NaN,2652612,985032
LAVORATO JOHN J,8000000,NaN,NaN,NaN,john.lavorato@enron.com,4158995,49537,2585,528,411,...,2035380,1552,False,1008149,NaN,339288,3962,7259,10425757,5167144
LAY KENNETH L,7000000,202911,-300000,NaN,kenneth.lay@enron.com,34348384,99832,36,123,16,...,3600000,10359729,True,14761694,NaN,1072321,2411,4273,103559793,49110078
LEFF DANIEL P,1000000,NaN,NaN,NaN,dan.leff@enron.com,NaN,NaN,63,67,14,...,1387399,3083,False,360528,NaN,273746,2672,2822,2664228,360528
LEMAISTRE CHARLES,NaN,NaN,-25000,112492,NaN,412878,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,87492,412878
LEWIS RICHARD,NaN,NaN,NaN,NaN,richard.lewis@enron.com,850477,NaN,26,10,0,...,NaN,NaN,False,NaN,NaN,NaN,739,952,NaN,850477
LINDHOLM TOD A,200000,204075,NaN,NaN,tod.lindholm@enron.com,2549361,57727,NaN,NaN,NaN,...,175000,2630,False,514847,NaN,236457,NaN,NaN,875889,3064208
LOCKHART EUGENE E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LOWRY CHARLES P,NaN,NaN,NaN,NaN,NaN,372205,NaN,NaN,NaN,NaN,...,NaN,NaN,False,153686,-153686,NaN,NaN,NaN,NaN,372205
MARTIN AMANDA K,NaN,85430,NaN,NaN,a..martin@enron.com,2070306,8211,230,8,0,...,5145434,2818454,False,NaN,NaN,349487,477,1522,8407016,2070306
MCCARTY DANNY J,NaN,NaN,NaN,NaN,danny.mccarty@enron.com,664375,NaN,215,25,2,...,NaN,NaN,False,94556,NaN,NaN,508,1433,NaN,758931
MCCLELLAN GEORGE,900000,NaN,-125000,NaN,george.mcclellan@enron.com,506765,228763,49,52,0,...,NaN,51587,False,441096,NaN,263413,1469,1744,1318763,947861
MCCONNELL MICHAEL S,1100000,NaN,NaN,NaN,mike.mcconnell@enron.com,1623010,81364,2742,92,194,...,554422,540,False,1478269,NaN,365038,2189,3329,2101364,3101279
MCDONALD REBECCA,NaN,NaN,NaN,NaN,rebecca.mcdonald@enron.com,757301,NaN,13,54,1,...,NaN,NaN,False,934065,NaN,NaN,720,894,NaN,1691366
MCMAHON JEFFREY,2600000,NaN,NaN,NaN,jeffrey.mcmahon@enron.com,1104054,137108,48,58,26,...,694862,297353,False,558801,NaN,370448,2228,2355,4099771,1662855
MENDELSOHN JOHN,NaN,NaN,-103750,103750,NaN,NaN,148,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,148,NaN
METTS MARK,600000,NaN,NaN,NaN,mark.metts@enron.com,NaN,94299,29,38,1,...,NaN,1740,False,585062,NaN,365788,702,807,1061827,585062
MEYER JEROME J,NaN,NaN,-38346,38346,NaN,NaN,2151,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,2151,NaN
MEYER ROCKFORD G,NaN,1848227,NaN,NaN,rockford.meyer@enron.com,493489,NaN,28,0,0,...,NaN,NaN,False,462384,NaN,NaN,22,232,1848227,955873
MORAN MICHAEL P,NaN,NaN,NaN,NaN,michael.moran@enron.com,59539,NaN,19,0,0,...,NaN,NaN,False,161602,NaN,NaN,127,672,NaN,221141
MORDAUNT KRISTINA M,325000,NaN,NaN,NaN,kristina.mordaunt@enron.com,NaN,35018,NaN,NaN,NaN,...,NaN,1411,False,208510,NaN,267093,NaN,NaN,628522,208510
MULLER MARK S,1100000,842924,-719000,NaN,s..muller@enron.com,1056320,NaN,16,12,0,...,1725545,947,False,360528,NaN,251654,114,136,3202070,1416848
MURRAY JULIA H,400000,NaN,NaN,NaN,julia.murray@enron.com,400478,57580,45,11,2,...,125000,330,False,196983,NaN,229284,395,2192,812194,597461
NOLES JAMES L,NaN,774401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,False,463261,-94556,NaN,NaN,NaN,774401,368705
OLSON CINDY K,750000,77716,NaN,NaN,cindy.olson@enron.com,1637034,63791,52,20,15,...,100000,972,False,969729,NaN,329078,856,1184,1321557,2606763
OVERDYKE JR JERE C,NaN,NaN,NaN,NaN,jere.overdyke@enron.com,5266578,18834,NaN,NaN,NaN,...,135836,176,False,2041016,NaN,94941,NaN,NaN,249787,7307594
PAI LOU L,1000000,NaN,NaN,NaN,lou.pai@enron.com,15364167,32047,NaN,NaN,NaN,...,NaN,1829457,False,8453763,NaN,261879,NaN,NaN,3123383,23817930
PEREIRA PAULO V. FERRAZ,NaN,NaN,-101250,101250,NaN,NaN,27942,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,27942,NaN
PICKERING MARK R,300000,NaN,NaN,NaN,mark.pickering@enron.com,28798,31653,67,7,0,...,NaN,NaN,False,NaN,NaN,655037,728,898,1386690,28798
PIPER GREGORY F,400000,1130036,-33333,NaN,greg.piper@enron.com,880290,43057,222,61,48,...,NaN,778,False,409554,-409554,197091,742,1238,1737629,880290
PIRO JIM,NaN,NaN,NaN,NaN,jim.piro@enron.com,NaN,NaN,16,0,1,...,NaN,NaN,False,47304,NaN,NaN,3,58,NaN,47304
POWERS WILLIAM,NaN,NaN,-17500,17500,ken.powers@enron.com,NaN,NaN,26,0,0,...,NaN,NaN,False,NaN,NaN,NaN,12,653,NaN,NaN
PRENTICE JAMES,NaN,564348,NaN,NaN,james.prentice@enron.com,886231,NaN,NaN,NaN,NaN,...,NaN,NaN,False,208809,NaN,NaN,NaN,NaN,564348,1095040
REDMOND BRIAN L,NaN,NaN,NaN,NaN,brian.redmond@enron.com,7509039,14689,221,204,49,...,NaN,NaN,False,381285,NaN,96840,1063,1671,111529,7890324
REYNOLDS LAWRENCE,100000,51365,-200000,NaN,NaN,4160672,8409,NaN,NaN,NaN,...,156250,202052,False,201483,-140264,76399,NaN,NaN,394475,4221891
RICE KENNETH D,1750000,NaN,-3504386,NaN,ken.rice@enron.com,19794175,46950,18,42,4,...,1617011,174839,True,2748364,NaN,420636,864,905,505050,22542539
RIEKER PAULA H,700000,214678,-100000,NaN,paula.rieker@enron.com,1635238,33271,82,35,48,...,NaN,1950,True,283649,NaN,249201,1258,1328,1099100,1918887
SAVAGE FRANK,NaN,NaN,-121284,125034,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,3750,NaN
SCRIMSHAW MATTHEW,NaN,NaN,NaN,NaN,matthew.scrimshaw@enron.com,759557,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,759557
SHANKMAN JEFFREY A,2000000,NaN,NaN,NaN,jeffrey.shankman@enron.com,1441898,178979,2681,94,83,...,554422,1191,False,630137,NaN,304110,1730,3221,3038702,2072035
SHAPIRO RICHARD S,650000,NaN,NaN,NaN,richard.shapiro@enron.com,607837,137767,1215,74,65,...,NaN,705,False,379164,NaN,269076,4527,15149,1057548,987001
SHARP VICTORIA T,600000,187469,NaN,NaN,vicki.sharp@enron.com,281073,116337,136,24,6,...,422158,2401,False,213063,NaN,248146,2477,3136,1576511,494136
SHELBY REX,200000,NaN,-4167,NaN,rex.shelby@enron.com,1624396,22884,39,13,14,...,NaN,1573324,True,869220,NaN,211844,91,225,2003885,2493616
SHERRICK JEFFREY B,NaN,NaN,NaN,NaN,jeffrey.sherrick@enron.com,1426469,NaN,25,39,18,...,NaN,NaN,False,405999,NaN,NaN,583,613,NaN,1832468
SHERRIFF JOHN R,1500000,NaN,NaN,NaN,john.sherriff@enron.com,1835558,NaN,92,28,23,...,554422,1852186,False,1293424,NaN,428780,2103,3187,4335388,3128982
SKILLING JEFFREY K,5600000,NaN,NaN,NaN,jeff.skilling@enron.com,19250000,29336,108,88,30,...,1920000,22122,True,6843672,NaN,1111258,2042,3627,8682716,26093672
STABLER FRANK,500000,NaN,NaN,NaN,frank.stabler@enron.com,NaN,16514,NaN,NaN,NaN,...,NaN,356071,False,511734,NaN,239502,NaN,NaN,1112087,511734
SULLIVAN-SHAKLOVITZ COLLEEN,100000,181993,NaN,NaN,NaN,1362375,NaN,NaN,NaN,NaN,...,554422,162,False,NaN,NaN,162779,NaN,NaN,999356,1362375
SUNDE MARTIN,700000,NaN,NaN,NaN,marty.sunde@enron.com,NaN,NaN,38,37,13,...,476451,111122,False,698920,NaN,257486,2565,2647,1545059,698920
TAYLOR MITCHELL S,600000,227449,NaN,NaN,mitchell.taylor@enron.com,3181250,NaN,29,0,0,...,NaN,NaN,False,563798,NaN,265214,300,533,1092663,3745048
THE TRAVEL AGENCY IN THE PARK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,362096,False,NaN,NaN,NaN,NaN,NaN,362096,NaN
THORN TERENCE H,NaN,16586,NaN,NaN,terence.thorn@enron.com,4452476,46145,41,0,0,...,200000,426629,False,365320,NaN,222093,73,266,911453,4817796
TILNEY ELIZABETH A,300000,NaN,-575000,NaN,elizabeth.tilney@enron.com,591250,NaN,19,10,11,...,275000,152055,False,576792,NaN,247338,379,460,399393,1168042
TOTAL,97343619,32083396,-27992891,1398517,NaN,311764000,5235198,NaN,NaN,NaN,...,48521928,42667589,False,130322299,-7576788,26704229,NaN,NaN,309886585,434509511
UMANOFF ADAM S,788750,NaN,NaN,NaN,adam.umanoff@enron.com,NaN,53122,18,12,0,...,NaN,NaN,False,NaN,NaN,288589,41,111,1130461,NaN
URQUHART JOHN A,NaN,NaN,-36666,36666,NaN,NaN,228656,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,228656,NaN
WAKEHAM JOHN,NaN,NaN,NaN,109298,NaN,NaN,103773,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,213071,NaN
WALLS JR ROBERT H,850000,NaN,NaN,NaN,rob.walls@enron.com,4346544,50936,146,17,0,...,540751,2,False,1552453,NaN,357091,215,671,1798780,5898997
WALTERS GARETH W,NaN,53625,NaN,NaN,NaN,1030329,33785,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,87410,1030329
WASAFF GEORGE,325000,831299,-583325,NaN,george.wasaff@enron.com,1668260,NaN,30,22,7,...,200000,1425,False,388167,NaN,259996,337,400,1034395,2056427
WESTFAHL RICHARD K,NaN,NaN,-10800,NaN,dick.westfahl@enron.com,NaN,51870,NaN,NaN,NaN,...,256191,401130,False,384930,NaN,63744,NaN,NaN,762135,384930
WHALEY DAVID A,NaN,NaN,NaN,NaN,NaN,98718,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,98718
WHALLEY LAWRENCE G,3000000,NaN,NaN,NaN,greg.whalley@enron.com,3282960,57838,556,186,24,...,808346,301026,False,2796177,NaN,510364,3920,6019,4677574,6079137
WHITE JR THOMAS E,450000,NaN,NaN,NaN,thomas.white@enron.com,1297049,81353,NaN,NaN,NaN,...,NaN,1085463,False,13847074,NaN,317543,NaN,NaN,1934359,15144123
WINOKUR JR. HERBERT S,NaN,NaN,-25000,108579,NaN,NaN,1413,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,84992,NaN
WODRASKA JOHN,NaN,NaN,NaN,NaN,john.wodraska@enron.com,NaN,NaN,NaN,NaN,NaN,...,NaN,189583,False,NaN,NaN,NaN,NaN,NaN,189583,NaN